services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-net

networks:
  jenkins-net:
    external: true # On utilise le même réseau que Jenkins