services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-net
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

networks:
  jenkins-net:
    external: true #utilise le même réseau que Jenkins

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: